module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    jison: {
      parser: {
        options: {
          moduleType: 'amd',
        },
        src: ["src/relalg.jison"],
        dest: "lib/parser.js",
      }
    },
    jison_amd_define: {
      parser: {
        options: {
          define: {
            tree: "Tree",
            relation: "Relation"
          }
        },
        src: ["lib/parser.js"]
      }
    },
    jshint: {
      options: {
        ignores: 'lib/parser.js', // The parser is auto-generated
        asi: true, // I'm not a great fan of unneeded semicolons 
        laxcomma: true // And I like having commas first
      },
      lib: ['lib/**/*.js'],
      test: {
        options: {
          loopfunc: true // For the tests, it's convient to define them in a loop
        },
        src: ['test/**/*.js']
      }
    },
    mochaTest: {
      test: {
        options: {
          reporter: 'spec'
        },
        src: ['test/**/*.js']
      }
    }
  })
  
  grunt.registerMultiTask('jison_amd_define', 'Modify the AMD define() statement generated by Jison', function() {
    grunt.task.requires('jison');

    var options = this.options({
      define: {}
    });

    var keys = [], values = [];
    for (key in options.define) {
      keys.push(key);
      values.push(options.define[key]);
    }

    var new_banner = 'define([\'' + keys.join('\', \'') + '\'], function(' + values.join(', ') + ') {';

    this.files.forEach(function(f) {
      var src = f.src.shift()
        , content = grunt.file.read(src)
        , lines = content.split(/\n\r?/)
        , EOL = require('os').EOL;
      lines[0] = new_banner;
      grunt.file.write(src, lines.join(EOL));
      grunt.log.oklns(src + " has gotten the define() improved");
    })
  })
  
  // Load extra Grunt tasks
  grunt.loadNpmTasks('grunt-contrib-jshint');
  grunt.loadNpmTasks('grunt-jison');
  grunt.loadNpmTasks('grunt-mocha-test');
  
  // Set up aliases
  grunt.registerTask('build', ['jison', 'jison_amd_define']);
  grunt.registerTask('test', ['mochaTest']);
}
